language: go
go: 1.x

branches:
  only:
    - master

env:
  - GO111MODULE=on

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.12.3
  - golangci-lint run -v --issues-exit-code=0 --disable-all -E=govet -E=errcheck -E=staticcheck -E=unused -E=gosimple -E=structcheck -E=varcheck -E=ineffassign -E=deadcode -E=typecheck -E=lll -E=gosec ./...

install:
  - go mod download

script:
  - go test ./...
